# See https://upptime.js.org/docs/configuration

owner: ElioDiNino
repo: status.eliodinino.com

delay: 5000 # 5 seconds
sites:
  - name: Personal Website
    url: https://eliodinino.com
    expectedStatusCodes:
      - 200
  
  - name: Personal Website (http)
    url: http://eliodinino.com
    
  - name: Personal Website (IPv4 - 443)
    url: eliodinino.com
    port: 443
    check: "tcp-ping"
    icon: https://raw.githubusercontent.com/ElioDiNino/eliodinino.com/main/website/public/favicon.ico
    
  - name: Personal Website (IPv4 - 80)
    url: eliodinino.com
    port: 80
    check: "tcp-ping"
    icon: https://raw.githubusercontent.com/ElioDiNino/eliodinino.com/main/website/public/favicon.ico
    
  - name: Personal Website (www - IPv4 - 443)
    url: www.eliodinino.com
    port: 443
    check: "tcp-ping"
    icon: https://raw.githubusercontent.com/ElioDiNino/eliodinino.com/main/website/public/favicon.ico
    
  - name: Personal Website (www - IPv4 - 80)
    url: www.eliodinino.com
    port: 80
    check: "tcp-ping"
    icon: https://raw.githubusercontent.com/ElioDiNino/eliodinino.com/main/website/public/favicon.ico
    
  - name: Personal Links Redirect (links)
    url: https://links.eliodinino.com
    icon: https://raw.githubusercontent.com/ElioDiNino/eliodinino.com/main/website/public/favicon.ico
    
  - name: Personal Links Redirect (links - IPv4 - 443)
    url: links.eliodinino.com
    port: 443
    check: "tcp-ping"
    icon: https://raw.githubusercontent.com/ElioDiNino/eliodinino.com/main/website/public/favicon.ico
    
  - name: Personal Links Redirect (links - IPv4 - 80)
    url: links.eliodinino.com
    port: 80
    check: "tcp-ping"
    icon: https://raw.githubusercontent.com/ElioDiNino/eliodinino.com/main/website/public/favicon.ico
    
  - name: Personal Links Redirect (bio)
    url: https://bio.eliodinino.com
    icon: https://raw.githubusercontent.com/ElioDiNino/eliodinino.com/main/website/public/favicon.ico

  - name: Personal Links Redirect (bio - IPv4 - 443)
    url: bio.eliodinino.com
    port: 443
    check: "tcp-ping"
    icon: https://raw.githubusercontent.com/ElioDiNino/eliodinino.com/main/website/public/favicon.ico
    
  - name: Personal Links Redirect (bio - IPv4 - 80)
    url: bio.eliodinino.com
    port: 80
    check: "tcp-ping"
    icon: https://raw.githubusercontent.com/ElioDiNino/eliodinino.com/main/website/public/favicon.ico
    
  - name: Photography Website Redirect
    url: https://photography.eliodinino.com
    icon: https://raw.githubusercontent.com/ElioDiNino/status.eliodinino.com/master/assets/camera.png
    
  - name: Photography Website
    url: https://eliodinino.wixsite.com/photography/
    icon: https://raw.githubusercontent.com/ElioDiNino/status.eliodinino.com/master/assets/camera.png
    
  - name: MTA-STS Policy Site
    url: https://mta-sts.eliodinino.com
    icon: https://raw.githubusercontent.com/ElioDiNino/status.eliodinino.com/master/assets/policy.png
    
  - name: GitHub Profile
    url: https://github.com/ElioDiNino
    icon: https://github.githubassets.com/favicons/favicon-dark.png
    
  - name: GitHub Profile (www)
    url: https://www.github.com/ElioDiNino
    icon: https://github.githubassets.com/favicons/favicon-dark.png
    
  - name: Personal Health Website
    url: https://health.eliodinino.com
    
  - name: Advanced RPAS Page
    url: https://tc.canada.ca/en/aviation/drone-safety/drone-pilot-licensing/getting-drone-pilot-certificate
    icon: https://www.canada.ca/etc/designs/canada/wet-boew/assets/favicon.ico

assignees:
  - ElioDiNino

status-website:
  cname: status.eliodinino.com
  logoUrl: https://raw.githubusercontent.com/ElioDiNino/eliodinino.com/main/website/public/site-logo.png
  favicon: https://raw.githubusercontent.com/ElioDiNino/eliodinino.com/main/website/public/favicon-96x96.png
  name: Status Page | Elio Di Nino
  introTitle: "Welcome to Elio Di Nino's status page"
  introMessage: This status page uses real-time data from my [GitHub repository](https://github.com/ElioDiNino/status.eliodinino.com)
  theme: night
  navbar:
    - title: Status
      href: /
    - title: Website
      href: https://eliodinino.com
    - title: GitHub
      href: https://github.com/$OWNER
  metaTags:
    - name: "robots"
      content: "noindex nofollow noarchive noimageindex"
  robotsText: "User-agent: *\n Disallow: /"

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"
